name: Firebase Hosting Deploy

on:
  push:
    branches:
      - master  # ou 'main', dependendo de qual branch está sendo usada

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseToken: ${{ secrets.FIREBASE_TOKEN }}  # Usando o FIREBASE_TOKEN aqui
          projectId: 'nosso-cantinho-fc205'  # Certifique-se de que o ID do seu projeto está correto
